/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/*${header:start}*/
#include "pin_mux.h"
#include "peripherals.h"
#include "fsl_clock.h"
#include "fsl_reset.h"
#include "board.h"
#include "app.h"
#include <stdbool.h>
/*${header:end}*/

/*${function:start}*/
void BOARD_InitHardware(void)
{
    BOARD_InitPins();
    BOARD_BootClockFRO12M();
    BOARD_InitBootPeripherals();

    /*
     * Red and green LED pins are shared with Arduino D5 and D6. Their GPIO
     * setup is generated by Config Tools and owned by the LCD shield.
     */
    LED_BLUE_INIT(LOGIC_LED_OFF);
}
/*${function:end}*/
