/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart_cmsis.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"
#include "fsl_lpadc.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define LPUART0_PERIPHERAL Driver_USART0
/* Definition of the clock source frequency */
#define LPUART0_CLOCK_SOURCE_FREQ 48000000UL
/* BOARD_InitPeripherals defines for LPI2C0 */
/* Definition of peripheral ID */
#define LPI2C0_PERIPHERAL LPI2C0
/* Definition of clock source */
#define LPI2C0_CLOCK_FREQ 12000000UL
/* Transfer buffer size */
#define LPI2C0_MASTER_BUFFER_SIZE 1
/* Definition of follower address */
#define LPI2C0_MASTER_SLAVE_ADDRESS 0
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpi2c_master_config_t LPI2C0_masterConfig;
extern lpi2c_master_transfer_t LPI2C0_masterTransfer;
extern uint8_t LPI2C0_masterBuffer[LPI2C0_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C0_masterHandle;
extern const lpadc_config_t ADC0_config;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Signal event function for component LPUART0*/
extern void LPUART0_SignalEvent(uint32_t event);
/* Get clock source frequency function for component LPUART0 */
uint32_t LPUART0_GetFreq(void);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
