/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse0 0x00u /*!<@brief Drive Strength Enable: Low */
#define PCR_IBE_ibe0 0x00u /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_INV_inv0 0x00u /*!<@brief Invert Input: Does not invert */
#define PCR_ODE_ode1 0x01u /*!<@brief Open Drain Enable: Enables */
#define PCR_PE_pe0 0x00u   /*!<@brief Pull Enable: Disables */
#define PCR_PE_pe1 0x01u   /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */
#define PCR_SRE_sre0 0x00u /*!<@brief Slew Rate Enable: Fast */

/*! @name PORT1_8 (number 2), RGBLCD1602_ARDUINO_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGBLCD1602_SDA_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGBLCD1602_SDA_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGBLCD1602_SDA_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_9 (number 3), RGBLCD1602_ARDUINO_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGBLCD1602_SCL_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGBLCD1602_SCL_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGBLCD1602_SCL_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_10 (number 4), KEYPAD_ARDUINO_A0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEYPAD_A0_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEYPAD_A0_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEYPAD_A0_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
