/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe0 0x00u            /*!<@brief Pull Enable: Disables */
#define PORT2_PCR0_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR30_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR31_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT3_12 (number 38), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_RED_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_13 (number 37), LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_0 (number 46), LED_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_7 (number 1), SW3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW3_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW3_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW3_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT1_10 (number 4), ARDUINO_A0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_A0_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_A0_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_A0_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT1_12 (number 6), ARDUINO_A1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_A1_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_A1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_A1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT1_13 (number 7), ARDUINO_A2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_A2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_A2_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_A2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT2_0 (number 14), ARDUINO_A3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_A3_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_A3_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_A3_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_31 (number 30), ARDUINO_A4
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_A4_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_A4_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_A4_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_30 (number 31), ARDUINO_A5
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ARDUINO_A5_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ARDUINO_A5_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ARDUINO_A5_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
