/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXA153
package_id: MCXA153VLH
mcu_data: ksdk2_0
processor_version: 26.03.20
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 9c69b39f-9abc-4e8a-8540-8e1714f5fb00
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - commonSetting:
    - USART_RX_BUFFER_LEN: '64'
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LPUART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART0'
- type: 'lpuart_cmsis'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpuart_cmsis_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART0'
- config_sets:
  - general:
    - main_config:
      - operationMode: 'ARM_USART_MODE_ASYNCHRONOUS'
      - clockSource: 'LpuartClock'
      - clockSourceFreq: 'BOARD_BootClockFRO12M'
      - power_state: 'ARM_POWER_FULL'
      - baudRate_Bps: '115200'
      - dataBits: 'ARM_USART_DATA_BITS_8'
      - parityBit: 'ARM_USART_PARITY_NONE'
      - stopBit: 'ARM_USART_STOP_BITS_1'
      - enableRX: 'false'
      - enableRXBuffer: 'true'
      - enableTX: 'false'
      - signalEventFunctionId: 'LPUART0_SignalEvent'
      - enableGetFreqFnCustomName: 'false'
      - getFreqFunctionCustomID: 'LPUART0_GetFreq'
      - enableInitPinsFnCustomName: 'false'
      - initPinFunctionCustomID: 'LPUART0_InitPins'
      - enableDeinitPinsFnCustomName: 'false'
      - deinitPinFunctionCustomID: 'LPUART0_DeinitPins'
  - fsl_cmsis_uart:
    - interrupt:
      - IRQn: 'LPUART0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
    - quick_selection: 'default_edma'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get clock source frequency */
uint32_t LPUART0_GetFreq(void){
  return LPUART0_CLOCK_SOURCE_FREQ;
};

static void LPUART0_init(void) {
  /* Initialize CMSIS USART */
  LPUART0_PERIPHERAL.Initialize(LPUART0_SignalEvent);
  /* Power control of CMSIS USART */
  LPUART0_PERIPHERAL.PowerControl(ARM_POWER_FULL);
  /* Control of CMSIS USART */
  LPUART0_PERIPHERAL.Control(ARM_USART_MODE_ASYNCHRONOUS | ARM_USART_DATA_BITS_8 | ARM_USART_PARITY_NONE | ARM_USART_STOP_BITS_1, 115200);
  /* Enable or disable receiver. */
  LPUART0_PERIPHERAL.Control(ARM_USART_CONTROL_RX , 0);
  /* Enable or disable transmitter. */
  LPUART0_PERIPHERAL.Control(ARM_USART_CONTROL_TX , 0);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  LPUART0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
