/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA153
package_id: MCXA153VLH
mcu_data: ksdk2_0
processor_version: 26.03.20
external_user_signals: {}
pin_labels:
- {pin_num: '62', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, label: TFT_D0_ARDUINO_D0, identifier: TFT_D0}
- {pin_num: '63', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, label: TFT_D1_ARDUINO_D1, identifier: TFT_D1}
- {pin_num: '18', pin_signal: P2_4/TRIG_OUT5/CT_INP14/CT1_MAT0, label: TFT_D2_ARDUINO_D2, identifier: TFT_D2}
- {pin_num: '46', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/CT_INP16/PWM0_A0, label: TFT_D3_LED_BLUE_ARDUINO_D3, identifier: TFT_D3}
- {pin_num: '19', pin_signal: P2_5/CT_INP15/CT1_MAT1, label: TFT_D4_ARDUINO_D4, identifier: TFT_D4}
- {pin_num: '38', pin_signal: P3_12/LPUART2_RTS_B/CT1_MAT2/PWM0_X0, label: TFT_D5_LED_RED_ARDUINO_D5, identifier: TFT_D5}
- {pin_num: '37', pin_signal: P3_13/LPUART2_CTS_B/CT1_MAT3/PWM0_X1, label: TFT_D6_LED_GREEN_ARDUINO_D6, identifier: TFT_D6}
- {pin_num: '45', pin_signal: P3_1/TRIG_IN1/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, label: TFT_D7_ARDUINO_D7, identifier: TFT_D7}
- {pin_num: '4', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT2_MAT0/ADC0_A8, label: TFT_RD_ARDUINO_A0, identifier: TFT_RD}
- {pin_num: '6', pin_signal: P1_12/WUU0_IN12/LPUART2_RXD/CT2_MAT2/ADC0_A10, label: TFT_WR_ARDUINO_A1, identifier: TFT_WR}
- {pin_num: '7', pin_signal: P1_13/TRIG_IN3/LPUART2_TXD/CT2_MAT3/ADC0_A11, label: TFT_CD_ARDUINO_A2, identifier: TFT_CD}
- {pin_num: '14', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, label: TFT_CS_ARDUINO_A3, identifier: TFT_CS}
- {pin_num: '30', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/CT0_MAT3/ADC0_A12, label: TFT_RESET_ARDUINO_A4, identifier: TFT_RESET}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

static void BOARD_InitOutputPin(PORT_Type *port, GPIO_Type *gpio, uint32_t pin, uint8_t output)
{
    gpio_pin_config_t config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = output,
    };

    PORT_SetPinMux(port, pin, kPORT_MuxAlt0);
    GPIO_PinInit(gpio, pin, &config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '62', peripheral: GPIO1, signal: 'GPIO, 4', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '63', peripheral: GPIO1, signal: 'GPIO, 5', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '18', peripheral: GPIO2, signal: 'GPIO, 4', pin_signal: P2_4/TRIG_OUT5/CT_INP14/CT1_MAT0, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '46', peripheral: GPIO3, signal: 'GPIO, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/CT_INP16/PWM0_A0, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '19', peripheral: GPIO2, signal: 'GPIO, 5', pin_signal: P2_5/CT_INP15/CT1_MAT1, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '38', peripheral: GPIO3, signal: 'GPIO, 12', pin_signal: P3_12/LPUART2_RTS_B/CT1_MAT2/PWM0_X0, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '37', peripheral: GPIO3, signal: 'GPIO, 13', pin_signal: P3_13/LPUART2_CTS_B/CT1_MAT3/PWM0_X1, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '45', peripheral: GPIO3, signal: 'GPIO, 1', pin_signal: P3_1/TRIG_IN1/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '4', peripheral: GPIO1, signal: 'GPIO, 10', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT2_MAT0/ADC0_A8, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '6', peripheral: GPIO1, signal: 'GPIO, 12', pin_signal: P1_12/WUU0_IN12/LPUART2_RXD/CT2_MAT2/ADC0_A10, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '7', peripheral: GPIO1, signal: 'GPIO, 13', pin_signal: P1_13/TRIG_IN3/LPUART2_TXD/CT2_MAT3/ADC0_A11, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '14', peripheral: GPIO2, signal: 'GPIO, 0', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '30', peripheral: GPIO3, signal: 'GPIO, 31', pin_signal: P3_31/LPTMR0_ALT2/TRIG_IN10/CT0_MAT3/ADC0_A12, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '51', peripheral: LPUART0, signal: RX, pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/I3C0_PUR}
  - {pin_num: '52', peripheral: LPUART0, signal: TX, pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/CMP0_OUT/CMP1_IN1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

void BOARD_InitPins(void)
{
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    CLOCK_EnableClock(kCLOCK_GateGPIO3);

    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);

    PORT_SetPinMux(PORT0, 2U, kPORT_MuxAlt2);
    PORT0->PCR[2] |= PORT_PCR_IBE(1U);
    PORT_SetPinMux(PORT0, 3U, kPORT_MuxAlt2);
    PORT0->PCR[3] |= PORT_PCR_IBE(1U);

    BOARD_InitOutputPin(PORT1, GPIO1, 4U, 0U);
    BOARD_InitOutputPin(PORT1, GPIO1, 5U, 0U);
    BOARD_InitOutputPin(PORT2, GPIO2, 4U, 0U);
    BOARD_InitOutputPin(PORT3, GPIO3, 0U, 0U);
    BOARD_InitOutputPin(PORT2, GPIO2, 5U, 0U);
    BOARD_InitOutputPin(PORT3, GPIO3, 12U, 0U);
    BOARD_InitOutputPin(PORT3, GPIO3, 13U, 0U);
    BOARD_InitOutputPin(PORT3, GPIO3, 1U, 0U);

    BOARD_InitOutputPin(PORT1, GPIO1, 10U, 1U);
    BOARD_InitOutputPin(PORT1, GPIO1, 12U, 1U);
    BOARD_InitOutputPin(PORT1, GPIO1, 13U, 1U);
    BOARD_InitOutputPin(PORT2, GPIO2, 0U, 1U);
    BOARD_InitOutputPin(PORT3, GPIO3, 31U, 1U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
