#ifndef LCD_DEMO_CONFIG_H_
#define LCD_DEMO_CONFIG_H_

#define LCD_KEYPAD_POLL_PERIOD_US 5000U
#define LCD_KEYPAD_DIAGNOSTIC_LOG_ENABLE 1
#define LCD_KEYPAD_DIAGNOSTIC_LOG_PERIOD_US 250000U

#endif /* LCD_DEMO_CONFIG_H_ */
