title: IPCEI NXP — Lecții FRDM-MCXA153
description: GenAI & Embedded Engineering — Școala de vară UPB-NXP 2026
theme: jekyll-theme-cayman

show_downloads: false

permalink: pretty

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
